### ISSUE TITLE
Les vidéos ne s'encodent pas par défaut

### ISSUE THREAD

**Issue by azmeuk** [yaal-coop/Esup-Pod#2]
Sans modification de la conf, les vidéos ne sont pas encodées à leur mise en ligne.

```python
pod-back-with-volumes         | Exception in thread Thread-13:
pod-back-with-volumes         | Traceback (most recent call last):
pod-back-with-volumes         |   File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
pod-back-with-volumes         |     self.run()
pod-back-with-volumes         |   File "/usr/local/lib/python3.9/threading.py", line 917, in run
pod-back-with-volumes         |     self._target(*self._args, **self._kwargs)
pod-back-with-volumes         |   File "/usr/src/app/pod/video_encode_transcript/encode.py", line 158, in encode_video
pod-back-with-volumes         |     encoding_video.start_encode()
pod-back-with-volumes         |   File "/usr/src/app/pod/video_encode_transcript/Encoding_video.py", line 775, in start_encode
pod-back-with-volumes         |     self.get_video_data()
pod-back-with-volumes         |   File "/usr/src/app/pod/video_encode_transcript/Encoding_video.py", line 242, in get_video_data
pod-back-with-volumes         |     streams = info.get("streams", [])
pod-back-with-volumes         | AttributeError: 'NoneType' object has no attribute 'get'
```

Il manque ffmpeg et ffpmpegthumbnailer qui peuvent être installés avec:

```shell
docker exec -it pod-back-with-volumes apt update
docker exec -it pod-back-with-volumes apt install --yes ffmpeg ffmpegthumbnailer
```

Ou alors, notre conf n'est pas bonne.

**Comment by azmeuk** [comment]
Peut-être lié à https://github.com/EsupPortail/Esup-Pod/commit/9aa6085b6b38b05ac7051f3cee8e7530da3686e0 ?
